sudo: required
services:
  - docker

before_install:
  - docker build -t superstorm42/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true superstorm42/react-test npm test

after_success:
  - docker build -t superstorm42/multi-client ./client
  - docker build -t superstorm42/multi-nginx ./nginx
  - docker build -t superstorm42/multi-server ./server
  - docker build -t superstorm42/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push superstorm42/multi-client
  - docker push superstorm42/multi-nginx
  - docker push superstorm42/multi-server
  - docker push superstorm42/multi-worker
